version: '2'
services:
  app:
    networks:
      - app
    build:
      context: ./haskell
    volumes:
      - ./haskell:/home/app
    environment:
      PGRST_IP_ADDR: ${PGRST_IP_ADDR}
      PGRST_PORT: ${PGRST_PORT}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_APP_ROLE: ${DB_APP_ROLE}
      APP_USER_JWT: ${APP_USER_JWT}
      MQ_KEY: ${MQ_KEY}
    depends_on:
      - postgrest
    ports:
      - "8000:8000"
  db:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - "./pgdata:/var/lib/postgresql/data"
    networks:
      app:
        ipv4_address: ${DB_IP_ADDR}
    ports:
      - "5433:5432"
  postgrest:
    build:
      context: ./postgrest
    ports:
      - "${PGRST_PORT}:${PGRST_PORT}"
    networks:
      app:
        ipv4_address: ${PGRST_IP_ADDR}
    volumes:
      - "./postgrest:/home"
    environment:
      DB_URI: ${DB_URI}
      DB_SCHEMA: ${DB_SCHEMA}
      DB_ANON_ROLE: ${DB_ANON_ROLE}
      DB_APP_ROLE: ${DB_APP_ROLE}
      DB_POOL: ${DB_POOL}
      PGRST_HOST: ${PGRST_HOST}
      PGRST_PORT: ${PGRST_PORT}
      PGRST_PROXY_URI: ${PGRST_PROXY_URI}
      PGRST_JWT_SECRET: ${PGRST_JWT_SECRET}
      PGRST_SECRET_IS_BASE64: ${PGRST_SECRET_IS_BASE64}
      PGRST_ROLE_CLAIM_KEY: ${PGRST_ROLE_CLAIM_KEY}
      PGRST_MAX_ROWS: ${PGRST_MAX_ROWS}
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    depends_on:
      - db

networks:
  app:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.0.1.0/24
          gateway: 172.0.1.1
